version: 2.1
jobs:
  build:
    working_directory: ~/rvsia-example-monorepo
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-deps
          command: yarn
      - run:
          name: build-packages
          command: yarn build
      - persist_to_workspace:
          root: ~/rvsia-example-monorepo
          paths:
              - "*"
  release:
    working_directory: ~/rvsia-example-monorepo
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: ~/rvsia-example-monorepo
      - run:
          name: Release new version
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/rvsia-example-monorepo/.npmrc
            yarn release

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - beta
